export const cardInfo = {
    artist: "Carl Critchlow",
    cmc: 11,
    color_identity: Array(0),
    colors: Array(0),
    image_uris: {
        art_crop: "https://img.scryfall.com/cards/art_crop/en/m10/208.jpg?1517813031",
        border_crop: "https://img.scryfall.com/cards/border_crop/en/m10/208.jpg?1517813031",
        large: "https://img.scryfall.com/cards/large/en/m10/208.jpg?1517813031",
        normal: "https://img.scryfall.com/cards/normal/en/m10/208.jpg?1517813031",
        png: "https://img.scryfall.com/cards/png/en/m10/208.png?1517813031",
        small: "https://img.scryfall.com/cards/small/en/m10/208.jpg?1517813031",
    },
    mana_cost: "{11}",
    name: "Darksteel Colossus",
    oracle_text: "Trample, indestructible↵If Darksteel Colossus would be put into a graveyard from anywhere, reveal Darksteel Colossus and shuffle it into its owner's library instead.",
    power: "11",
    rarity: "mythic",
    reserved: false,
    setName: undefined,
    toughness: "11",
    typeLine: "Artifact Creature — Golem",
}

interface CardInfo {
    artist: string,
    cmc: number,
    color_identity: Array<string>,
    colors: Array<string>,
    image_uris: {
        art_crop: string,
        border_crop: string,
        large: string,
        normal: string,
        png: string,
        small: string
    },
    mana_cost: string,
    name: string,
    oracle_text: string,
    power: string,
    rarity: string,
    reserved: boolean,
    setName: string,
    toughness: string,
    typeLine: string,
}